spring:
  application:
    name: random-game-config-server

  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/dulfinne/random-game-config.git
          clone-on-start: true
          basedir: file://c:/tmp/git-c
          username: dulfinne
          password: ${GITHUB_CONFIG_TOKEN}
          default-label: main

server:
  port: 8888
