name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper executable
        run: chmod +x ./random-game-config-server/gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        working-directory: ./random-game-config-server

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: random-game-config-server-jar
          path: ./random-game-config-server/build/libs/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: random-game-config-server-jar
          path: ./build/libs/

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/random-game-config-server
          TAG=develop-${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest ./random-game-config-server

      - name: Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/random-game-config-server
          TAG=develop-${GITHUB_SHA::7}
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
